spring.application.name=sportsdata

# Connessione al database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sportsdata
spring.datasource.username=postgres
spring.datasource.password=Coca-Cola1886
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JWT Configuration
# La chiave deve essere una stringa casuale molto lunga (almeno 256 bit / 32 caratteri per HS256)
jwt.secret=QuestaEunaChiaveSegretaMoltoLungaPerIlProgettoSocialSportsData12345!
# Scadenza del token in millisecondi (es. 24 ore = 86400000 ms)
jwt.expiration=86400000